### ISSUE TITLE
How to change color ?

### ISSUE THREAD

**Issue by jadjay** [danihodovic/steeef#1]
Hi, I love your zsh theme, it's quick, readable, and very intuitive with git.

But... As I put this theme on all of my servers/desktop sometimes I don't quickly see where am I.

Is it possible to change the color from the .zshrc ? Or even with another trick ?

Thanks,

**Comment by danihodovic** [comment]
Hi Jadjay,

I'm not maintaining this zsh theme as I'm using a customized theme. You can fork the repository and change the following lines:

https://github.com/danihodovic/steeef/blob/master/steeef.zsh-theme#L33-L46
