### ISSUE TITLE
Change position of env name

### ISSUE THREAD

**Issue by motapaolla** [danihodovic/steeef#3]
First of all completely in love with your theme. 

Just wanted to kindly ask you to make this modification or let me know how to make it myself:

```
(base) 
user_name at pc_name in ~/Workspace/myproject (dev) 
$ ls
```

To:
```
(base) user_name at pc_name in ~/Workspace/myproject (dev) 
$ ls
```

**Comment by danihodovic** [comment]
I don't use this myself any longer, but you could fork the project and remove the line break here: https://github.com/danihodovic/steeef/blob/master/steeef.zsh-theme#L92-L93

**Comment by motapaolla** [comment]
Ok, thank you so much!
